### ISSUE TITLE
Need Xmodem with TLS for secure communciation

### ISSUE THREAD

**Issue by rajeshnaikaj** [emancipatedMind/XmodemProtocol#1]
Please provide TLS with the xmodem protocol to communicate in a secure way in C# .Net

**Comment by emancipatedMind** [comment]
Hello rajeshnaikaj,

This implementation of the XModem Protocol is just that. If you wanted to extend it, and include headers on each packet using a private, public key system to ensure authentication for each packet or something like that, I don't see why that wouldn't work.

Thanks.

I will close this issue as this isn't an issue with the project per se, but more of a request for a separate piece of software.
