### ISSUE TITLE
Could this library detect the client side's received packet?

### ISSUE THREAD

**Issue by LJSJ123** [emancipatedMind/XmodemProtocol#10]
I have another question about this library.

If my computer is the local side and my SAS card is the client side, 

how to use this library to detect received packet on SAS card?

Here is the flowchart:
local side want to sent packet→use XmodemProtocol  to send→After sending packet→client side receive packet

You said if you're sending, you're not receiving. 

From my understanding, this library could only detect send and receive on local side not on client side.

Sorry, I just want to make sure what you mean.

**Comment by emancipatedMind** [comment]
I will answer this just to close the issue.

You are essentially asking for two way communication. This is supported as the receiver must acknowledge that it received a valid packet with ACK.

You know what was sent as you can monitor that, and the receiver should acknowlegde. This, to me, is what you're looking for unless I misunderstood the question.

Thanks.
