### ISSUE TITLE
Timeout Option

### ISSUE THREAD

**Issue by fatihyildizhan** [emancipatedMind/XmodemProtocol#2]
Hi,

Your library is working perfectly, thank you.

I just couldn't handle one case which is about the timeout.

I am initializing timeout durations like this. 

```
xmodem.Options = new XModemProtocolOptions
{
 SenderInitializationTimeout = 3000,
 ReceiverInitializationTimeout = 3000,
 ReceiverTimeoutDuringPacketReception = 3000
 };
```

After this, I am calling `xmodem.PacketToSend` and `xmodem.Send();`

Then I am detaching the data cable. So, COM port stays but there is no more Data cable. Timeout is not triggering. Then `xmodem.Send()` throws InvalidOperationException and this locks my UI totally. 

Even try-catch handles the error.

How can I handle COM port exists but there is no data cable. Which means xmodem cannot send data.

Thanks

**Comment by emancipatedMind** [comment]
I'm sorry. I'm not really understanding. Are you allowing a couple of packets to transfer, and pulling the plug to simulate a lost connection?
