### ISSUE TITLE
Delay after ACK response

### ISSUE THREAD

**Issue by stukdev** [emancipatedMind/XmodemProtocol#4]
Hi, your library is working well, but i notice a delay when you receive an ACK packet that cause the trasfert time consuming.
For example:
This is the the trasfert using xmodem protocol by other software, You can see a 8.9ms delay between packet sent

![immagine](https://user-images.githubusercontent.com/8056730/100618454-29e66d00-331c-11eb-89da-0c4131320f86.png)

And this is using your library, you can see a 26.7ms delay between packet sent

![immagine](https://user-images.githubusercontent.com/8056730/100618614-5b5f3880-331c-11eb-8dfe-a42f0d15d40b.png)

Is there a way to improve this delay?
Thanks
Stefano

**Comment by emancipatedMind** [comment]
Let me see if I can understand what you are saying.

Here, the XModemCommunicator is in the sender role.

When it receives an ACK from the receiver, it then takes about 7x as long as other software to begin sending the next packet?

I am saying 7x because looking at time, it looks like about 6ms for the receive to respond. Subtracting that from both durations, it goes from about 3ms to about 21ms.

**Comment by stukdev** [comment]
Yes, sure.
The latency is caused by the ReadAllBytes() function. For test i use this and this port the latency to 9ms like the other software.

```
public virtual List<byte> ReadAllBytes() {
            List<byte> byteList = new List<byte>();
            byte[] byteArray;
            //do {
                int bytesToRead = Port.BytesToRead;
                byteArray = new byte[bytesToRead];
                Port.Read(byteArray, 0, bytesToRead);
                byteList.AddRange(byteArray);
                //System.Threading.Tasks.Task.Delay(10).Wait();
           // } while (Port.BytesToRead > 0);
            return byteList;
        }
```

**Comment by emancipatedMind** [comment]
Yes.

I do remember this now. In my particular application, I was having issues with speed, and slowed down the reading considerably. The only line that should be edited out is the System.Threading.Tasks.Task.Delay(10).Wait().

If you need the communicator to work differently, you can always write your own implementation of the ICommunicator interface, and pass that in.

My apologies for the delayed response here.
